<script setup>
import { Head, useForm, usePage } from '@inertiajs/vue3';
import { computed, nextTick, ref, watch } from 'vue';
import AppButton from '../../../Components/AppButton.vue';
import AppCard from '../../../Components/AppCard.vue';
import AppDatePicker from '../../../Components/AppDatePicker.vue';
import AppCurrencyInput from '../../../Components/AppCurrencyInput.vue';
import AppIcon from '../../../Components/AppIcon.vue';
import AppInput from '../../../Components/AppInput.vue';
import AppModal from '../../../Components/AppModal.vue';
import AppTextarea from '../../../Components/AppTextarea.vue';
import SmartSelect from '../../../Components/SmartSelect.vue';
import AuthenticatedLayout from '../../../Layouts/AuthenticatedLayout.vue';

const props = defineProps({
    loanOptions: { type: Array, required: true },
    installmentOptions: { type: Array, required: true },
    cashAccounts: { type: Array, required: true },
    peminjamOptions: { type: Array, required: true },
    today: { type: String, required: true },
});

const page = usePage();
const pagePath = '/accounting/journal-entries/installment';
const form = useForm({
    transaction_date: props.today,
    loan_id: '',
    installment_row_id: '',
    installment_number: '',
    principal_amount: '',
    interest_amount: '',
    penalty_amount: '',
    cash_account_row_id: '',
    description: '',
    reference: '',
    member_allocations: [],
});

const availableInstallments = computed(() => props.installmentOptions.filter((i) => i.loan_row_id === Number(form.loan_id)));

const availablePeminjam = computed(() => props.peminjamOptions.filter((p) => p.loan_row_id === Number(form.loan_id)));

const autoInstallment = computed(() => {
    if (! form.transaction_date || ! availableInstallments.value.length) return null;
    const candidates = availableInstallments.value
        .filter((i) => i.due_date <= form.transaction_date)
        .filter((i) => (i.principal_sisa > 0 || i.interest_sisa > 0))
        .sort((a, b) => b.due_date.localeCompare(a.due_date) || b.installment_number - a.installment_number);
    return candidates[0] ?? null;
});

const selectedInstallment = computed(() => availableInstallments.value.find((i) => i.value === Number(form.installment_row_id)) ?? null);

function applyInstallmentDefaults(target) {
    if (! target) return;
    form.principal_amount = target.principal_sisa || '';
    form.interest_amount = target.interest_sisa || '';
}

watch(() => form.loan_id, () => {
    form.installment_row_id = '';
    form.installment_number = '';
    form.principal_amount = '';
    form.interest_amount = '';
    form.reference = '';
    form.member_allocations = [];
    resetAllocationModal();
});

watch(() => form.transaction_date, () => {
    if (autoInstallment.value) {
        form.installment_row_id = autoInstallment.value.value;
        form.installment_number = autoInstallment.value.value;
        applyInstallmentDefaults(autoInstallment.value);
    }
});

watch([selectedInstallment, () => form.principal_amount, () => form.interest_amount], () => {
    if (selectedInstallment.value) {
        form.installment_number = selectedInstallment.value.value;
    }
});

const totalAmount = computed(() => {
    const principal = Number(form.principal_amount) || 0;
    const interest = Number(form.interest_amount) || 0;
    const penalty = Number(form.penalty_amount) || 0;
    return principal + interest + penalty;
});

const selectedLoan = computed(() => props.loanOptions.find((l) => l.value === Number(form.loan_id)) ?? null);
const selectedPeminjam = computed(() => availablePeminjam.value.find((p) => p.value === Number(form.reference)) ?? null);

function autoGenerateDescription() {
    if (! selectedLoan.value) return '';

    const productCode = selectedLoan.value.product_code?.toUpperCase() ?? '';
    const groupName = selectedLoan.value.group_name;
    const installment = selectedInstallment.value ?? autoInstallment.value;
    const installmentNumber = installment?.installment_number ?? null;
    const payer = selectedPeminjam.value?.label.replace(/^#\d+\s*·\s*/, '') ?? null;

    const principal = Number(form.principal_amount) || 0;
    const interest = Number(form.interest_amount) || 0;
    const penalty = Number(form.penalty_amount) || 0;

    const breakdown = [];
    if (principal > 0) breakdown.push(`Pokok ${currency(principal)}`);
    if (interest > 0) breakdown.push(`Jasa ${currency(interest)}`);
    if (penalty > 0) breakdown.push(`Denda ${currency(penalty)}`);

    const sentences = [];

    let main = 'Angsuran';
    if (productCode) main += ` ${productCode}`;
    if (installmentNumber) main += ` ke-${installmentNumber}`;
    if (groupName) main += ` Kelompok ${groupName}`;
    if (payer) main += ` a/n ${payer}`;
    sentences.push(main);

    if (breakdown.length) {
        sentences.push(`Rincian: ${breakdown.join(', ')}`);
    }

    return sentences.join('. ');
}

watch([selectedLoan, () => autoInstallment.value, selectedPeminjam], () => {
    form.description = autoGenerateDescription();
}, { immediate: true });

function currency(value) {
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(value ?? 0);
}

function submit() {
    form.post(pagePath, {
        preserveScroll: true,
        onSuccess: () => {
            form.reset('principal_amount', 'interest_amount', 'penalty_amount', 'cash_account_row_id', 'installment_row_id', 'reference', 'description');
            form.transaction_date = props.today;
        },
    });
}

const flash = computed(() => page.props.flash?.success);
const flashEntry = computed(() => (typeof flash.value === 'object' ? flash.value : null));
const flashLines = computed(() => flashEntry.value?.lines ?? []);
const debitedLines = computed(() => flashLines.value.filter((line) => line.debit > 0));
const creditedLines = computed(() => flashLines.value.filter((line) => line.credit > 0));

const successCardRef = ref(null);
watch(flashEntry, (entry) => {
    if (entry) {
        nextTick(() => successCardRef.value?.root?.scrollIntoView({ behavior: 'smooth', block: 'start' }));
    }
});

const installmentLabel = computed(() => {
    const target = selectedInstallment.value ?? autoInstallment.value;
    if (! target) return '—';
    return `Angsuran ke-${target.installment_number} · Jatuh tempo ${target.due_date}`;
});

// === Modal: Detail Kelompok ===
const groupModalOpen = ref(false);
const groupDetail = ref(null);
const groupLoading = ref(false);
async function openGroupModal() {
    if (!selectedLoan.value) return;
    groupModalOpen.value = true;
    groupLoading.value = true;
    try {
        groupDetail.value = await fetchJson(`/accounting/loans/${selectedLoan.value.value}/group-detail`);
    } finally {
        groupLoading.value = false;
    }
}

async function fetchJson(url) {
    const response = await fetch(url, { headers: { Accept: 'application/json' }, credentials: 'same-origin' });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return response.json();
}

// === Modal: Riwayat Angsuran ===
const historyModalOpen = ref(false);
const historyRows = ref([]);
const historyLoading = ref(false);
async function openHistoryModal() {
    if (!selectedLoan.value) return;
    historyModalOpen.value = true;
    historyLoading.value = true;
    try {
        const data = await fetchJson(`/accounting/loans/${selectedLoan.value.value}/installment-history`);
        historyRows.value = data.rows ?? [];
    } finally {
        historyLoading.value = false;
    }
}

// === Modal: Catatan Per-Anggota ===
const allocationModalOpen = ref(false);
const allocationMembers = ref([]);
const allocationRows = ref([]);
const allocationLoading = ref(false);

function resetAllocationModal() {
    allocationMembers.value = [];
    allocationRows.value = [];
}

const allocationTotals = computed(() => {
    return allocationRows.value.reduce((acc, r) => {
        acc.principal += Number(r.principal_paid) || 0;
        acc.interest += Number(r.interest_paid) || 0;
        acc.penalty += Number(r.penalty_paid) || 0;
        return acc;
    }, { principal: 0, interest: 0, penalty: 0 });
});

const allocationMismatch = computed(() => {
    const expectedPrincipal = Number(form.principal_amount) || 0;
    const expectedInterest = Number(form.interest_amount) || 0;
    const expectedPenalty = Number(form.penalty_amount) || 0;
    return {
        principal: Math.round(allocationTotals.value.principal * 100) / 100 !== Math.round(expectedPrincipal * 100) / 100,
        interest: Math.round(allocationTotals.value.interest * 100) / 100 !== Math.round(expectedInterest * 100) / 100,
        penalty: Math.round(allocationTotals.value.penalty * 100) / 100 !== Math.round(expectedPenalty * 100) / 100,
    };
});


const allocationSelisih = computed(() => {
    const expectedPrincipal = Number(form.principal_amount) || 0;
    const expectedInterest = Number(form.interest_amount) || 0;
    const expectedPenalty = Number(form.penalty_amount) || 0;
    const diffPrincipal = Math.round((allocationTotals.value.principal - expectedPrincipal) * 100) / 100;
    const diffInterest = Math.round((allocationTotals.value.interest - expectedInterest) * 100) / 100;
    const diffPenalty = Math.round((allocationTotals.value.penalty - expectedPenalty) * 100) / 100;
    const hasDiff = diffPrincipal !== 0 || diffInterest !== 0 || diffPenalty !== 0;
    return { diffPrincipal, diffInterest, diffPenalty, hasDiff };
});

function selisihLabel(diff) {
    if (diff === 0) return null;
    const abs = Math.abs(diff);
    const formatted = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(abs);
    return diff > 0 ? `Lebih ${formatted}` : `Kurang ${formatted}`;
}

async function openAllocationModal() {
    if (!selectedLoan.value) return;
    allocationModalOpen.value = true;
    allocationLoading.value = true;
    try {
        const data = await fetchJson(`/accounting/loans/${selectedLoan.value.value}/member-options`);
        const members = data.members ?? [];
        allocationMembers.value = members;
        allocationRows.value = prefillAllocations(members);
    } finally {
        allocationLoading.value = false;
    }
}

function prefillAllocations(members) {
    const memberCount = members.length;
    const principal = Number(form.principal_amount) || 0;
    const interest = Number(form.interest_amount) || 0;
    const penalty = Number(form.penalty_amount) || 0;
    const totalAllocated = members.reduce((sum, m) => sum + (Number(m.allocated_amount) || 0), 0);
    const useProportional = totalAllocated > 0;
    return members.map((m) => {
        const ratio = useProportional
            ? (Number(m.allocated_amount) || 0) / totalAllocated
            : (memberCount > 0 ? 1 / memberCount : 0);
        return {
            member_row_id: m.value,
            full_name: m.label,
            allocated_amount: Number(m.allocated_amount) || 0,
            principal_paid: Math.round(principal * ratio * 100) / 100,
            interest_paid: Math.round(interest * ratio * 100) / 100,
            penalty_paid: Math.round(penalty * ratio * 100) / 100,
        };
    });
}

function applyAllocationToForm() {
    form.member_allocations = allocationRows.value.map((r) => ({
        member_row_id: r.member_row_id,
        principal_paid: Number(r.principal_paid) || 0,
        interest_paid: Number(r.interest_paid) || 0,
        penalty_paid: Number(r.penalty_paid) || 0,
    }));
    form.principal_amount = Math.round(allocationTotals.value.principal * 100) / 100;
    form.interest_amount = Math.round(allocationTotals.value.interest * 100) / 100;
    form.penalty_amount = Math.round(allocationTotals.value.penalty * 100) / 100;
}

function balanceAllocationRemainder(field) {
    // Even out any rounding remainder to the first row so totals match exactly.
    const expected = {
        principal_paid: Number(form.principal_amount) || 0,
        interest_paid: Number(form.interest_amount) || 0,
        penalty_paid: Number(form.penalty_amount) || 0,
    }[field];
    if (allocationRows.value.length === 0 || expected === 0) return;
    const sum = allocationRows.value.reduce((acc, r) => acc + (Number(r[field]) || 0), 0);
    const diff = Math.round((expected - sum) * 100) / 100;
    if (diff !== 0) {
        allocationRows.value[0][field] = Math.round(((Number(allocationRows.value[0][field]) || 0) + diff) * 100) / 100;
    }
}
</script>

<template>
    <Head title="Jurnal Angsuran" />
    <AuthenticatedLayout>
        <div class="mx-auto max-w-7xl space-y-6">
            <header>
                <h1 class="text-2xl font-bold text-primary sm:text-3xl">Input Jurnal Angsuran</h1>
                <p class="mt-1 text-on-surface-variant">Catat pembayaran angsuran pinjaman dengan akun debit kas dan kredit piutang/jasa/denda.</p>
            </header>

            <AppCard v-if="flashEntry" ref="successCardRef">
                <div class="mb-5 flex items-start gap-3">
                    <div class="grid size-12 shrink-0 place-items-center rounded-full bg-secondary-container text-secondary">
                        <AppIcon name="check_circle" class="text-2xl" />
                    </div>
                    <div class="min-w-0 flex-1">
                        <p class="text-base font-bold text-primary">{{ flashEntry.message }}</p>
                        <p class="mt-1 text-sm text-on-surface-variant">
                            <span class="font-semibold">{{ flashEntry.entry.transaction_date }}</span>
                            <span v-if="flashEntry.entry.journal_number"> · No. {{ flashEntry.entry.journal_number }}</span>
                            <span v-else-if="flashEntry.entry.id"> · #{{ flashEntry.entry.id }}</span>
                        </p>
                        <p v-if="flashEntry.entry.description" class="mt-1 text-sm text-on-surface-variant">{{ flashEntry.entry.description }}</p>
                    </div>
                    <a
                        v-if="flashEntry.receipt_url"
                        :href="flashEntry.receipt_url"
                        target="_blank"
                        rel="noopener"
                        class="shrink-0"
                    >
                        <AppButton type="button" variant="secondary" icon="print" size="compact">
                            Cetak Bukti
                        </AppButton>
                    </a>
                </div>

                <div class="grid gap-4 sm:grid-cols-2">
                    <div class="rounded-xl border border-secondary/30 bg-secondary-container/40 p-4">
                        <div class="mb-3 flex items-center gap-2">
                            <AppIcon name="arrow_downward" class="text-secondary" />
                            <p class="text-xs font-bold uppercase tracking-wider text-secondary">Akun Bertambah (Debit)</p>
                        </div>
                        <ul class="space-y-2">
                            <li v-for="line in debitedLines" :key="`d-${line.account_code}`" class="rounded-lg bg-surface-container-lowest p-3">
                                <p class="text-sm font-bold text-primary">{{ line.account_code }} · {{ line.account_name }}</p>
                                <p class="mt-1 text-base font-bold text-secondary">{{ currency(line.debit) }}</p>
                            </li>
                            <li v-if="!debitedLines.length" class="text-sm text-on-surface-variant">Tidak ada akun debit.</li>
                        </ul>
                    </div>
                    <div class="rounded-xl border border-error/30 bg-error-container/40 p-4">
                        <div class="mb-3 flex items-center gap-2">
                            <AppIcon name="arrow_outward" class="text-error" />
                            <p class="text-xs font-bold uppercase tracking-wider text-error">Akun Berkurang (Kredit)</p>
                        </div>
                        <ul class="space-y-2">
                            <li v-for="line in creditedLines" :key="`c-${line.account_code}`" class="rounded-lg bg-surface-container-lowest p-3">
                                <p class="text-sm font-bold text-primary">{{ line.account_code }} · {{ line.account_name }}</p>
                                <p class="mt-1 text-base font-bold text-error">{{ currency(line.credit) }}</p>
                            </li>
                            <li v-if="!creditedLines.length" class="text-sm text-on-surface-variant">Tidak ada akun kredit.</li>
                        </ul>
                    </div>
                </div>
            </AppCard>

            <AppCard>
                <form class="space-y-5" @submit.prevent="submit">
                    <SmartSelect v-model="form.loan_id" :options="props.loanOptions" label="Pinjaman" placeholder="Cari pinjaman..." required searchable search-placeholder="Cari pinjaman..." hint="Loan dengan status aktif atau sudah dicairkan" />

                    <div class="grid gap-4 sm:grid-cols-2">
                        <AppDatePicker v-model="form.transaction_date" label="Tanggal Angsuran" required :error="form.errors.transaction_date" />
                        <AppInput :model-value="installmentLabel" label="Angsuran ke-N" readonly hint="Otomatis dari tanggal; pilih pinjaman untuk melihat daftar" />
                    </div>

                    <div class="grid gap-4 sm:grid-cols-2">
                        <AppCurrencyInput v-model="form.principal_amount" label="Pokok" icon="payments" :min="1" required :error="form.errors.principal_amount" placeholder="0" />
                        <AppCurrencyInput v-model="form.interest_amount" label="Jasa" icon="payments" :min="0" required :error="form.errors.interest_amount" placeholder="0" />
                    </div>

                    <div class="grid gap-4 sm:grid-cols-2">
                        <AppCurrencyInput v-model="form.penalty_amount" label="Denda" icon="payments" :min="0" :error="form.errors.penalty_amount" placeholder="0" />
                        <AppInput :model-value="currency(totalAmount)" label="Total (Pokok + Jasa + Denda)" readonly icon="calculate" />
                    </div>

                    <div class="grid gap-4 sm:grid-cols-2">
                        <SmartSelect v-model="form.reference" :options="availablePeminjam" label="Penyetor" :placeholder="form.loan_id ? 'Pilih peminjam' : 'Pilih pinjaman dulu'" :disabled="!form.loan_id" required :error="form.errors.reference" searchable search-placeholder="Cari peminjam..." />
                        <SmartSelect v-model="form.cash_account_row_id" :options="props.cashAccounts" label="Tujuan (Akun Debit)" placeholder="Pilih akun kas" required :error="form.errors.cash_account_row_id" />
                    </div>

                    <input type="hidden" :value="form.description">

                    <div class="flex flex-wrap items-center justify-between gap-2 border-t border-outline-variant pt-4">
                        <div class="flex flex-wrap gap-2">
                            <AppButton variant="secondary" icon="groups" type="button" :disabled="!selectedLoan" @click="openGroupModal">Detail Kelompok</AppButton>
                            <AppButton variant="secondary" icon="history" type="button" :disabled="!selectedLoan" @click="openHistoryModal">Riwayat Angsuran</AppButton>
                            <AppButton variant="secondary" icon="person" type="button" :disabled="!selectedLoan" @click="openAllocationModal">Catatan Per-Anggota</AppButton>
                        </div>
                        <div class="flex gap-2">
                            <a :href="pagePath"><AppButton variant="secondary" type="button">Reset</AppButton></a>
                            <AppButton type="submit" :loading="form.processing" :disabled="form.processing" icon="save">Catat Jurnal Angsuran</AppButton>
                        </div>
                    </div>
                </form>
            </AppCard>

            <AppModal v-model="groupModalOpen" title="Detail Kelompok" size="lg">
                <div v-if="groupLoading" class="py-8 text-center text-on-surface-variant">Memuat…</div>
                <div v-else-if="groupDetail?.group" class="space-y-5">
                    <div class="grid gap-4 sm:grid-cols-2">
                        <div><p class="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Kode</p><p class="mt-1 font-bold text-primary">{{ groupDetail.group.code }}</p></div>
                        <div><p class="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Nama Kelompok</p><p class="mt-1 font-bold text-primary">{{ groupDetail.group.name }}</p></div>
                        <div><p class="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Jumlah Anggota</p><p class="mt-1 font-bold text-primary">{{ groupDetail.group.member_count }} orang</p></div>
                        <div v-if="groupDetail.group.phone"><p class="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Telepon</p><p class="mt-1 font-bold text-primary">{{ groupDetail.group.phone }}</p></div>
                        <div v-if="groupDetail.group.address" class="sm:col-span-2"><p class="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Alamat</p><p class="mt-1 font-bold text-primary">{{ groupDetail.group.address }}</p></div>
                    </div>
                    <div>
                        <h3 class="mb-3 text-sm font-bold uppercase tracking-wider text-primary">Daftar Anggota</h3>
                        <ul v-if="groupDetail.members?.length" class="divide-y divide-outline-variant rounded-lg border border-outline-variant">
                            <li v-for="m in groupDetail.members" :key="m.row_id" class="flex items-center justify-between p-3 text-sm">
                                <span class="font-bold text-primary">#{{ m.row_id }} · {{ m.full_name }}</span>
                                <span class="text-on-surface-variant">{{ m.status }}</span>
                            </li>
                        </ul>
                        <p v-else class="text-sm text-on-surface-variant">Belum ada anggota terdaftar.</p>
                    </div>
                </div>
                <div v-else class="py-8 text-center text-on-surface-variant">Kelompok tidak ditemukan untuk pinjaman ini.</div>
            </AppModal>

            <AppModal v-model="historyModalOpen" title="Riwayat Angsuran" size="full">
                <div v-if="historyLoading" class="py-8 text-center text-on-surface-variant">Memuat…</div>
                <div v-else-if="historyRows.length" class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead class="bg-surface-container-low text-xs uppercase tracking-wider text-on-surface-variant">
                            <tr>
                                <th class="px-3 py-2 text-left">Tanggal</th>
                                <th class="px-3 py-2 text-left">No. Jurnal</th>
                                <th class="px-3 py-2 text-left">Angsuran</th>
                                <th class="px-3 py-2 text-left">Keterangan</th>
                                <th class="px-3 py-2 text-right">Catatan Per-Anggota</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="row in historyRows" :key="row.id" class="border-t border-outline-variant align-top">
                                <td class="px-3 py-3 font-bold text-primary">{{ row.transaction_date }}</td>
                                <td class="px-3 py-3 text-primary">{{ row.journal_number || '—' }}</td>
                                <td class="px-3 py-3 text-primary">{{ row.tracking[0]?.installment_number ? `ke-${row.tracking[0].installment_number}` : '—' }}</td>
                                <td class="px-3 py-3 text-on-surface-variant">{{ row.description }}</td>
                                <td class="px-3 py-3">
                                    <ul v-if="row.tracking.length" class="space-y-1.5">
                                        <li v-for="t in row.tracking" :key="`${row.id}-${t.member_row_id}`" class="rounded-md bg-surface-container-low px-2 py-1 text-xs">
                                            <p class="font-bold text-primary">{{ t.full_name }}</p>
                                            <p class="text-on-surface-variant">Pokok {{ currency(t.principal_paid) }} · Jasa {{ currency(t.interest_paid) }}<span v-if="t.penalty_paid > 0"> · Denda {{ currency(t.penalty_paid) }}</span></p>
                                        </li>
                                    </ul>
                                    <span v-else class="text-xs text-on-surface-variant">Tidak ada catatan.</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div v-else class="py-8 text-center text-on-surface-variant">Belum ada jurnal angsuran terposting untuk pinjaman ini.</div>
            </AppModal>

            <AppModal v-model="allocationModalOpen" title="Catatan Angsuran Per-Anggota" size="lg">
                <div v-if="allocationLoading" class="py-8 text-center text-on-surface-variant">Memuat…</div>
                <div v-else-if="allocationMembers.length" class="space-y-4">
                    <p class="text-sm text-on-surface-variant">Atur nominal Pokok, Jasa, dan Denda per anggota. Nilai awal dihitung proporsional sesuai alokasi pinjaman masing-masing.</p>
                    <div class="overflow-x-auto">
                        <table class="w-full text-sm">
                            <thead class="bg-surface-container-low text-xs uppercase tracking-wider text-on-surface-variant">
                                <tr>
                                    <th class="px-3 py-2 text-left">Anggota</th>
                                    <th class="px-3 py-2 text-right">Alokasi</th>
                                    <th class="px-3 py-2 text-right">Pokok</th>
                                    <th class="px-3 py-2 text-right">Jasa</th>
                                    <th class="px-3 py-2 text-right">Denda</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="(row, idx) in allocationRows" :key="row.member_row_id" class="border-t border-outline-variant">
                                    <td class="px-3 py-3 font-bold text-primary">{{ row.full_name }}</td>
                                    <td class="px-3 py-2 text-right text-on-surface-variant">{{ currency(row.allocated_amount) }}</td>
                                    <td class="px-3 py-2"><AppCurrencyInput v-model="allocationRows[idx].principal_paid" placeholder="0" /></td>
                                    <td class="px-3 py-2"><AppCurrencyInput v-model="allocationRows[idx].interest_paid" placeholder="0" /></td>
                                    <td class="px-3 py-2"><AppCurrencyInput v-model="allocationRows[idx].penalty_paid" placeholder="0" /></td>
                                </tr>
                            </tbody>
                            <tfoot class="border-t-2 border-outline-variant bg-surface-container-low text-xs">
                                <tr>
                                    <td class="px-3 py-2 font-bold uppercase text-on-surface-variant">Total</td>
                                    <td></td>
                                    <td class="px-3 py-2 text-right font-bold" :class="allocationMismatch.principal ? 'text-error' : 'text-primary'">{{ currency(allocationTotals.principal) }}<span v-if="allocationMismatch.principal" class="ml-1 text-error">≠</span></td>
                                    <td class="px-3 py-2 text-right font-bold" :class="allocationMismatch.interest ? 'text-error' : 'text-primary'">{{ currency(allocationTotals.interest) }}<span v-if="allocationMismatch.interest" class="ml-1 text-error">≠</span></td>
                                    <td class="px-3 py-2 text-right font-bold" :class="allocationMismatch.penalty ? 'text-error' : 'text-primary'">{{ currency(allocationTotals.penalty) }}<span v-if="allocationMismatch.penalty" class="ml-1 text-error">≠</span></td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <div v-if="allocationSelisih.hasDiff" class="rounded-lg border border-outline-variant bg-surface-container-low px-4 py-3 text-sm">
                        <p class="mb-1 font-bold text-on-surface-variant">Selisih dengan form angsuran kelompok:</p>
                        <ul class="space-y-0.5">
                            <li v-if="allocationSelisih.diffPrincipal !== 0" :class="allocationSelisih.diffPrincipal > 0 ? 'text-tertiary' : 'text-error'">Pokok: <span class="font-semibold">{{ selisihLabel(allocationSelisih.diffPrincipal) }}</span></li>
                            <li v-if="allocationSelisih.diffInterest !== 0" :class="allocationSelisih.diffInterest > 0 ? 'text-tertiary' : 'text-error'">Jasa: <span class="font-semibold">{{ selisihLabel(allocationSelisih.diffInterest) }}</span></li>
                            <li v-if="allocationSelisih.diffPenalty !== 0" :class="allocationSelisih.diffPenalty > 0 ? 'text-tertiary' : 'text-error'">Denda: <span class="font-semibold">{{ selisihLabel(allocationSelisih.diffPenalty) }}</span></li>
                        </ul>
                        <p class="mt-1 text-xs text-on-surface-variant">Saat diterapkan, nominal pada form angsuran kelompok akan otomatis diperbarui sesuai total di atas.</p>
                    </div>
                    <div class="flex flex-wrap justify-end gap-2">
                        <AppButton variant="secondary" type="button" icon="balance" @click="() => { balanceAllocationRemainder('principal_paid'); balanceAllocationRemainder('interest_paid'); balanceAllocationRemainder('penalty_paid'); }">Ratakan Selisih</AppButton>
                    </div>
                </div>
                <div v-else class="py-8 text-center text-on-surface-variant">Pinjaman ini tidak terkait kelompok. Catatan per-anggota tidak tersedia.</div>
                <template #footer>
                    <AppButton variant="secondary" type="button" @click="allocationModalOpen = false">Batal</AppButton>
                    <AppButton type="button" icon="check" @click="() => { applyAllocationToForm(); allocationModalOpen = false; }">Terapkan ke Form</AppButton>
                </template>
            </AppModal>
        </div>
    </AuthenticatedLayout>
</template>
