<script setup>
import { Head, useForm, usePage } from '@inertiajs/vue3';
import { computed, nextTick, ref, watch } from 'vue';
import AppButton from '../../../Components/AppButton.vue';
import AppCard from '../../../Components/AppCard.vue';
import AppDatePicker from '../../../Components/AppDatePicker.vue';
import AppCurrencyInput from '../../../Components/AppCurrencyInput.vue';
import AppIcon from '../../../Components/AppIcon.vue';
import AppInput from '../../../Components/AppInput.vue';
import AppModal from '../../../Components/AppModal.vue';
import AuthenticatedLayout from '../../../Layouts/AuthenticatedLayout.vue';

const props = defineProps({
    loanOptions: { type: Array, required: true },
    installmentOptions: { type: Array, required: true },
    cashAccounts: { type: Array, required: true },
    peminjamOptions: { type: Array, required: true },
    today: { type: String, required: true },
});

const page = usePage();
const submitUrl = '/accounting/journal-entries/installment-individual';
const form = useForm({
    transaction_date: props.today,
    loan_id: '',
    installment_row_id: '',
    installment_number: '',
    principal_amount: '',
    interest_amount: '',
    penalty_amount: '',
    cash_account_row_id: '',
    description: '',
    reference: '',
    is_individual: 1,
});

const availableInstallments = computed(() => props.installmentOptions.filter((i) => i.loan_row_id === Number(form.loan_id)));

// Pencarian ringan untuk konfirmasi identitas peminjam (perorangan = 1 orang
// per loan, jadi tidak perlu SmartSelect dropdown — cukup cek substring match
// terhadap subject_label / borrower_member_row_id).
const memberSearch = ref('');
const memberSearchPlaceholder = 'Ketik nama/NIK/ID anggota untuk konfirmasi';
const memberVerified = computed(() => {
    const q = memberSearch.value.trim().toLocaleLowerCase();
    if (!q) return false;
    const subject = (selectedLoan.value?.subject_label ?? '').toLocaleLowerCase();
    const memberId = String(selectedLoan.value?.borrower_member_row_id ?? '');
    return subject.includes(q) || memberId === q;
});
watch(() => form.loan_id, () => { memberSearch.value = ''; });

const autoInstallment = computed(() => {
    if (! form.transaction_date || ! availableInstallments.value.length) return null;
    const candidates = availableInstallments.value
        .filter((i) => i.due_date <= form.transaction_date)
        .filter((i) => (i.principal_sisa > 0 || i.interest_sisa > 0))
        .sort((a, b) => b.due_date.localeCompare(a.due_date) || b.installment_number - a.installment_number);
    return candidates[0] ?? null;
});

const selectedInstallment = computed(() => availableInstallments.value.find((i) => i.value === Number(form.installment_row_id)) ?? null);

function applyInstallmentDefaults(target) {
    if (! target) return;
    form.principal_amount = target.principal_sisa || '';
    form.interest_amount = target.interest_sisa || '';
}

watch(() => form.loan_id, () => {
    form.installment_row_id = '';
    form.installment_number = '';
    form.principal_amount = '';
    form.interest_amount = '';
    // Untuk pinjaman perorangan hanya ada 1 peminjam (member utama) yang
    // otomatis ter-set dari borrower_member_row_id saat loan dipilih.
    const loan = props.loanOptions.find((l) => l.value === Number(form.loan_id));
    // Auto-pre-select anggota dari peminjamOptions (searchable) sehingga user
    // tetap bisa melihat/mengkonfirmasi identitas sebelum submit.
    form.reference = loan?.borrower_member_row_id ?? '';
});

watch(() => form.transaction_date, () => {
    if (autoInstallment.value) {
        form.installment_row_id = autoInstallment.value.value;
        form.installment_number = autoInstallment.value.value;
        applyInstallmentDefaults(autoInstallment.value);
    }
});

watch([selectedInstallment, () => form.principal_amount, () => form.interest_amount], () => {
    if (selectedInstallment.value) {
        form.installment_number = selectedInstallment.value.value;
    }
});

const totalAmount = computed(() => {
    const principal = Number(form.principal_amount) || 0;
    const interest = Number(form.interest_amount) || 0;
    const penalty = Number(form.penalty_amount) || 0;
    return principal + interest + penalty;
});

const selectedLoan = computed(() => props.loanOptions.find((l) => l.value === Number(form.loan_id)) ?? null);

function autoGenerateDescription() {
    if (! selectedLoan.value) return '';

    const productCode = selectedLoan.value.product_code?.toUpperCase() ?? '';
    const installment = selectedInstallment.value ?? autoInstallment.value;
    const installmentNumber = installment?.installment_number ?? null;
    const subject = selectedLoan.value.subject_label ?? '—';

    const principal = Number(form.principal_amount) || 0;
    const interest = Number(form.interest_amount) || 0;
    const penalty = Number(form.penalty_amount) || 0;

    const breakdown = [];
    if (principal > 0) breakdown.push(`Pokok ${currency(principal)}`);
    if (interest > 0) breakdown.push(`Jasa ${currency(interest)}`);
    if (penalty > 0) breakdown.push(`Denda ${currency(penalty)}`);

    const sentences = [];

    let main = 'Angsuran';
    if (productCode) main += ` ${productCode}`;
    if (installmentNumber) main += ` ke-${installmentNumber}`;
    main += ` Individu a/n ${subject}`;
    sentences.push(main);

    if (breakdown.length) {
        sentences.push(`Rincian: ${breakdown.join(', ')}`);
    }

    return sentences.join('. ');
}

watch([selectedLoan, () => autoInstallment.value], () => {
    form.description = autoGenerateDescription();
}, { immediate: true });

function currency(value) {
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(value ?? 0);
}

function submit() {
    form.post(submitUrl, {
        preserveScroll: true,
        onSuccess: () => {
            form.reset('principal_amount', 'interest_amount', 'penalty_amount', 'cash_account_row_id', 'installment_row_id', 'reference', 'description');
            form.transaction_date = props.today;
            memberSearch.value = '';
            // Re-generate description setelah reset (watch tidak trigger karena loan belum berubah).
            form.description = autoGenerateDescription();
        },
    });
}

const flash = computed(() => page.props.flash?.success);
const flashEntry = computed(() => (typeof flash.value === 'object' ? flash.value : null));
const flashLines = computed(() => flashEntry.value?.lines ?? []);
const debitedLines = computed(() => flashLines.value.filter((line) => line.debit > 0));
const creditedLines = computed(() => flashLines.value.filter((line) => line.credit > 0));

const successCardRef = ref(null);
watch(flashEntry, (entry) => {
    if (entry) {
        nextTick(() => successCardRef.value?.root?.scrollIntoView({ behavior: 'smooth', block: 'start' }));
    }
});

const installmentLabel = computed(() => {
    const target = selectedInstallment.value ?? autoInstallment.value;
    if (! target) return '—';
    return `Angsuran ke-${target.installment_number} · Jatuh tempo ${target.due_date}`;
});

// === Modal: Riwayat Angsuran ===
const historyModalOpen = ref(false);
const historyRows = ref([]);
const historyLoading = ref(false);
async function openHistoryModal() {
    if (!selectedLoan.value) return;
    historyModalOpen.value = true;
    historyLoading.value = true;
    try {
        const data = await fetchJson(`/accounting/loans/${selectedLoan.value.value}/installment-history`);
        historyRows.value = data.rows ?? [];
    } finally {
        historyLoading.value = false;
    }
}

async function fetchJson(url) {
    const response = await fetch(url, { headers: { Accept: 'application/json' }, credentials: 'same-origin' });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return response.json();
}
</script>

<template>
    <Head title="Jurnal Angsuran Individu" />
    <AuthenticatedLayout>
        <div class="mx-auto max-w-7xl space-y-6">
            <header>
                <h1 class="text-2xl font-bold text-primary sm:text-3xl">Input Jurnal Angsuran Individu</h1>
                <p class="mt-1 text-on-surface-variant">Catat pembayaran angsuran pinjaman perorangan dengan akun debit kas dan kredit piutang/jasa/denda. Setiap angsuran hanya untuk satu peminjam.</p>
            </header>

            <AppCard v-if="flashEntry" ref="successCardRef">
                <div class="mb-5 flex items-start gap-3">
                    <div class="grid size-12 shrink-0 place-items-center rounded-full bg-secondary-container text-secondary">
                        <AppIcon name="check_circle" class="text-2xl" />
                    </div>
                    <div class="min-w-0 flex-1">
                        <p class="text-base font-bold text-primary">{{ flashEntry.message }}</p>
                        <p class="mt-1 text-sm text-on-surface-variant">
                            <span class="font-semibold">{{ flashEntry.entry.transaction_date }}</span>
                            <span v-if="flashEntry.entry.journal_number"> · No. {{ flashEntry.entry.journal_number }}</span>
                            <span v-else-if="flashEntry.entry.id"> · #{{ flashEntry.entry.id }}</span>
                        </p>
                        <p v-if="flashEntry.entry.description" class="mt-1 text-sm text-on-surface-variant">{{ flashEntry.entry.description }}</p>
                    </div>
                    <a
                        v-if="flashEntry.receipt_url"
                        :href="flashEntry.receipt_url"
                        target="_blank"
                        rel="noopener"
                        class="shrink-0"
                    >
                        <AppButton type="button" variant="secondary" icon="print" size="compact">
                            Cetak Bukti
                        </AppButton>
                    </a>
                </div>

                <div class="grid gap-4 sm:grid-cols-2">
                    <div class="rounded-xl border border-secondary/30 bg-secondary-container/40 p-4">
                        <div class="mb-3 flex items-center gap-2">
                            <AppIcon name="arrow_downward" class="text-secondary" />
                            <p class="text-xs font-bold uppercase tracking-wider text-secondary">Akun Bertambah (Debit)</p>
                        </div>
                        <ul class="space-y-2">
                            <li v-for="line in debitedLines" :key="`d-${line.account_code}`" class="rounded-lg bg-surface-container-lowest p-3">
                                <p class="text-sm font-bold text-primary">{{ line.account_code }} · {{ line.account_name }}</p>
                                <p class="mt-1 text-base font-bold text-secondary">{{ currency(line.debit) }}</p>
                            </li>
                            <li v-if="!debitedLines.length" class="text-sm text-on-surface-variant">Tidak ada akun debit.</li>
                        </ul>
                    </div>
                    <div class="rounded-xl border border-error/30 bg-error-container/40 p-4">
                        <div class="mb-3 flex items-center gap-2">
                            <AppIcon name="arrow_outward" class="text-error" />
                            <p class="text-xs font-bold uppercase tracking-wider text-error">Akun Berkurang (Kredit)</p>
                        </div>
                        <ul class="space-y-2">
                            <li v-for="line in creditedLines" :key="`c-${line.account_code}`" class="rounded-lg bg-surface-container-lowest p-3">
                                <p class="text-sm font-bold text-primary">{{ line.account_code }} · {{ line.account_name }}</p>
                                <p class="mt-1 text-base font-bold text-error">{{ currency(line.credit) }}</p>
                            </li>
                            <li v-if="!creditedLines.length" class="text-sm text-on-surface-variant">Tidak ada akun kredit.</li>
                        </ul>
                    </div>
                </div>
            </AppCard>

            <AppCard>
                <form class="space-y-5" @submit.prevent="submit">
                    <SmartSelect v-model="form.loan_id" :options="props.loanOptions" label="Pinjaman Perorangan" placeholder="Cari pinjaman..." required searchable search-placeholder="Cari pinjaman..." hint="Loan perorangan dengan status aktif atau sudah dicairkan" />

                    <div v-if="selectedLoan?.subject_label" class="rounded-xl border border-outline-variant bg-surface-container-lowest p-4 shadow-sm">
                        <div class="flex items-start gap-3">
                            <span class="flex size-9 shrink-0 items-center justify-center rounded-xl bg-secondary-container text-secondary">
                                <AppIcon name="person" class="text-lg" />
                            </span>
                            <div class="min-w-0 flex-1">
                                <p class="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant">Peminjam</p>
                                <p class="mt-0.5 text-base font-bold text-primary break-words">{{ selectedLoan.subject_label }}</p>
                                <p v-if="selectedLoan.borrower_member_row_id" class="mt-0.5 text-xs text-on-surface-variant">ID Anggota #{{ selectedLoan.borrower_member_row_id }}</p>
                            </div>
                        </div>
                        <div class="mt-3 flex items-center gap-2 border-t border-outline-variant pt-3">
                            <AppIcon name="search" class="text-base text-on-surface-variant" />
                            <input
                                v-model="memberSearch"
                                type="search"
                                class="h-8 flex-1 rounded-md border border-outline-variant bg-surface-container-lowest px-2.5 text-xs text-primary placeholder:text-on-surface-variant focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                                :placeholder="memberSearchPlaceholder"
                            >
                            <AppIcon v-if="memberVerified" name="check_circle" class="text-base text-secondary" />
                        </div>
                        <p v-if="memberSearch && !memberVerified" class="mt-2 text-[11px] text-on-surface-variant">Tidak ada kecocokan dengan "{{ memberSearch }}". Pastikan nama/NIK sesuai.</p>
                        <p v-else-if="memberVerified" class="mt-2 text-[11px] font-semibold text-secondary">Kecocokan terkonfirmasi.</p>
                    </div>

                    <div class="grid gap-4 sm:grid-cols-2">
                        <AppDatePicker v-model="form.transaction_date" label="Tanggal Angsuran" required :error="form.errors.transaction_date" />
                        <AppInput :model-value="installmentLabel" label="Angsuran ke-N" readonly hint="Otomatis dari tanggal; pilih pinjaman untuk melihat daftar" />
                    </div>

                    <div class="grid gap-4 sm:grid-cols-2">
                        <AppCurrencyInput v-model="form.principal_amount" label="Pokok" icon="payments" :min="1" required :error="form.errors.principal_amount" placeholder="0" />
                        <AppCurrencyInput v-model="form.interest_amount" label="Jasa" icon="payments" :min="0" required :error="form.errors.interest_amount" placeholder="0" />
                    </div>

                    <div class="grid gap-4 sm:grid-cols-2">
                        <AppCurrencyInput v-model="form.penalty_amount" label="Denda" icon="payments" :min="0" :error="form.errors.penalty_amount" placeholder="0" />
                        <AppInput :model-value="currency(totalAmount)" label="Total (Pokok + Jasa + Denda)" readonly icon="calculate" />
                    </div>

                    <div class="grid gap-4 sm:grid-cols-2">
                        <SmartSelect v-model="form.cash_account_row_id" :options="props.cashAccounts" label="Tujuan (Akun Debit)" placeholder="Pilih akun kas" required :error="form.errors.cash_account_row_id" />
                    </div>

                    <input type="hidden" :value="form.description">
                    <input type="hidden" :value="form.reference">

                    <div class="flex flex-wrap items-center justify-between gap-2 border-t border-outline-variant pt-4">
                        <div class="flex flex-wrap gap-2">
                            <AppButton variant="secondary" icon="history" type="button" :disabled="!selectedLoan" @click="openHistoryModal">Riwayat Angsuran</AppButton>
                        </div>
                        <div class="flex gap-2">
                            <a :href="submitUrl"><AppButton variant="secondary" type="button">Reset</AppButton></a>
                            <AppButton type="submit" :loading="form.processing" :disabled="form.processing" icon="save">Catat Jurnal Angsuran</AppButton>
                        </div>
                    </div>
                </form>
            </AppCard>

            <AppModal v-model="historyModalOpen" title="Riwayat Angsuran" size="full">
                <div v-if="historyLoading" class="py-8 text-center text-on-surface-variant">Memuat…</div>
                <div v-else-if="historyRows.length" class="overflow-x-auto">
                    <table class="w-full text-sm">
                        <thead class="bg-surface-container-low text-xs uppercase tracking-wider text-on-surface-variant">
                            <tr>
                                <th class="px-3 py-2 text-left">Tanggal</th>
                                <th class="px-3 py-2 text-left">No. Jurnal</th>
                                <th class="px-3 py-2 text-left">Angsuran</th>
                                <th class="px-3 py-2 text-left">Keterangan</th>
                                <th class="px-3 py-2 text-right">Pokok</th>
                                <th class="px-3 py-2 text-right">Jasa</th>
                                <th class="px-3 py-2 text-right">Denda</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="row in historyRows" :key="row.id" class="border-t border-outline-variant align-top">
                                <td class="px-3 py-3 font-bold text-primary">{{ row.transaction_date }}</td>
                                <td class="px-3 py-3 text-primary">{{ row.journal_number || '—' }}</td>
                                <td class="px-3 py-3 text-primary">{{ row.tracking[0]?.installment_number ? `ke-${row.tracking[0].installment_number}` : '—' }}</td>
                                <td class="px-3 py-3 text-on-surface-variant">{{ row.description }}</td>
                                <td class="px-3 py-3 text-right text-primary">{{ currency(row.tracking[0]?.principal_paid || 0) }}</td>
                                <td class="px-3 py-3 text-right text-primary">{{ currency(row.tracking[0]?.interest_paid || 0) }}</td>
                                <td class="px-3 py-3 text-right text-primary">{{ currency(row.tracking[0]?.penalty_paid || 0) }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div v-else class="py-8 text-center text-on-surface-variant">Belum ada jurnal angsuran terposting untuk pinjaman ini.</div>
            </AppModal>
        </div>
    </AuthenticatedLayout>
</template>
